import "~/styles/globals.css";
import "~/styles/ytvideo.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "myBCPS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body
        className="dark h-[100vh] bg-cover bg-center bg-repeat text-left text-white"
        style={{
          backgroundImage:
            "url('https://directus.bloxvalschools.com/assets/25fc5f22-e187-48df-a483-259ddc1238e7?format=webp')",
        }}
      >
        <TRPCReactProvider>
          <div className="fixed top-0 z-50 flex h-[100vh] w-[100vw] items-center justify-center bg-black/75">
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
